### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by lITronusIl** [InfinityFreeHosting/contactform#10]
Hi, where exactly are the lines for the cookies? I want to remove the phpsessid cookie, but cant find it in the index.

**Comment by HansAdema** [comment]
There are no lines for cookies. The contact form makes use of PHP sessions for form response messages, and PHP creates a `PHPSESSID` cookie to track the session.

You can remove the `session_start` and `$_SESSION` references from all files if you really don't want these cookies, but the form won't work properly unless you figure out another way to handle error messages.
