### ISSUE TITLE
How to change charset=iso-8859-1?

### ISSUE THREAD

**Issue by homespunphilosopher** [InfinityFreeHosting/contactform#11]
Hi there. Thank you for the form. I need some other charset for the outgoing mail, perhaps UTF-8, but I can't find where it can be set.

**Comment by HansAdema** [comment]
The contact form doesn't have any configuration for alternative charsets right now, it just uses the default from PHPMailer, which is indeed ISO-8859-1.

It should be fairly easy to add though.
