### ISSUE TITLE
Problem with this script

### ISSUE THREAD

**Issue by B0binch0** [InfinityFreeHosting/contactform#15]
When I upload the file in filemanage and try to use contact form it gives me this error HTTP ERROR 500
![d](https://github.com/InfinityFreeHosting/contactform/assets/157300245/1d9c07c8-89d9-46f4-865f-2a3659352d98)
any suggestions how i can fix it?
kinds regards,
B0binch0

**Comment by Grendel7** [comment]
HTTP ERROR 500 means your PHP code has crashed. Please see this guide from the InfinityFree KB about how to start troubleshooting it:

https://forum.infinityfree.com/t/http-error-500/49352

Please note that this is the issue tracker for the contact form, i.e. this is the place to discuss issues with the software. Please only post here if you have a clear, verified and reproducible issue with the contact form.

 "It's not working and I don't know why" is not necessarily a software issue, it could also be a problem with your setup or configuration.

And an issue tracker is not a support ticket system for you to have someone hold your hand with installation.

So until you can prove that this is a problem with the contact form, with clear reproduction steps, please troubleshoot the issue yourself first.
