### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by yijiechoo16163** [InfinityFreeHosting/contactform#2]
This page isn’t working
my-domain.epizy.com is currently unable to handle this request.
HTTP ERROR 500
Above is the error message from Google Chrome. I don't know why like that. 
Please help me solve this issues. Thank you.
![error](https://user-images.githubusercontent.com/63585997/85135477-bb7f8800-b270-11ea-9a67-cb655c8f13b3.png)
I think it is PHP Error : https://support.infinityfree.net/websites/http-error-500/

**Comment by ShirkerZ** [comment]
You need to download the last version of contactform which contains the vendor folder.[https://github.com/InfinityFreeHosting/contactform/releases](url)
