### ISSUE TITLE
re-Captcha giving error

### ISSUE THREAD

**Issue by dluigi** [InfinityFreeHosting/contactform#3]
re-Captcha giving error every time I'm trying to verify I'm a human.
After succeeding the verification and submitting the form, I'm getting an error says:
"Please retry the CAPTCHA"
ALL the settings are correct.
[https://i.imgur.com/I9jfVc2.png](https://i.imgur.com/I9jfVc2.png)

**Comment by greenreader9** [comment]
Are you still having the issue? The form has been updated, so maybe try downloading and setting up the newest version. (You should update even if it is working as the update fixed a security issue)
