### ISSUE TITLE
The form must be submitted with POST data.

### ISSUE THREAD

**Issue by greenreader9** [InfinityFreeHosting/contactform#5]
Hello,
I have used this form on multiple projects (Its awesome), and today I was trying to implement it into a new one. I keep getting the "The form must be submitted with POST data." Error, and I know it's not my fault (Or at least I don't believe it is) since my other projects (Who's files I haven't touched) also return the same error. Is there a fix for this, or will I have to find a alternative?
Thanks.

![image](https://user-images.githubusercontent.com/75644395/120867904-7b381900-c558-11eb-9a20-ecd1c5fcc6d3.png)

**Comment by HansAdema** [comment]
> I know it's not my fault (Or at least I don't believe it is) since my other projects (Who's files I haven't touched) also return the same error

What do you mean by this exactly? You say all your project give POST related error and therefore assume that the problem must be that all the scripts being broken without any changes?

The `<form>` tag in the template has `method="post"`, so it should be submitted as post. I think this may be a browser or hosting/server/domain issue, not a code issue.

**Comment by greenreader9** [comment]
Never mind, the issue had to do with some faulty .htaccess code. I thought it was the contact forms fault since it was the only thing effected. Thanks for the amazing forum.
