### ISSUE TITLE
After all configuration my contact page does'nt open anymore

### ISSUE THREAD

**Issue by AmariLuigi** [InfinityFreeHosting/contactform#8]
![image](https://user-images.githubusercontent.com/84550313/160392947-49a670c5-9734-4e50-8ac8-278225b3f0c2.png)

**Comment by HansAdema** [comment]
It means your page crashed. Please see this KB article on InfinityFree for more information: https://forum.infinityfree.net/t/http-error-500/49352

This is probably not an issue with the code, but with your configuration.

Please ask about this on the InfinityFree forum instead.
