### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by lITronusIl** [InfinityFreeHosting/contactform#9]
Hi, how can i remove the captcha function?

**Comment by HansAdema** [comment]
It's fairly easy to do so. Just remove all of these lines:

- https://github.com/InfinityFreeHosting/contactform/blob/master/index.php#L81-L83
- https://github.com/InfinityFreeHosting/contactform/blob/master/index.php#L31-L32
- https://github.com/InfinityFreeHosting/contactform/blob/master/submit.php#L14-L37

You'll also want to remove these from your config.php file: https://github.com/InfinityFreeHosting/contactform/blob/master/config.example.php#L24-L26

If you're building from source, you can also remove recaptcha from the composer.json and run `composer update`  to remove it from the vendor folder. But it's not necessary to do so, and not feasible if you're using the prebuilt zip file from the releases.
